### ISSUE TITLE
Is `discord-module-search` only made for macOS builds?

### ISSUE THREAD

**Issue by Bettlee** [samuelthomas2774/discord-module-search#18]
Hi, I was wondering if this plugin was supported on Windows as well. I'm not sure what to do with the file extension, `.bd`?

**Comment by samuelthomas2774** [comment]
This plugin requires a specific version of BetterDiscord, which is no longer being developed and won't work with current versions of Discord.

I didn't test it on Windows while that version of BetterDiscord was being developed but there's no reason it shouldn't have worked on Windows.
